{{- $secretPrefix := include "%%% APPLICATION_NAME %%%.fullname" . -}}
{{- $namespace := .Release.Namespace -}}
{{- range .Values.containers -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $secretPrefix .name | trunc 63 | trimSuffix "-" }} 
  namespace: {{ $namespace }}
data:
{{ toYaml .secret | nindent 2 }}
---
{{- end -}}
{{- with .Values.httpdContainer }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $secretPrefix .name | trunc 63 | trimSuffix "-" }} 
  namespace: {{ $namespace }}
data:
{{ toYaml .secret | nindent 2 }}
{{- end -}}
