{{- $organizationHost := printf "%s.organization.org" .Chart.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    organization.org/host: {{ $organizationHost }}
{{ include "%%% APPLICATION_NAME %%%.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "%%% APPLICATION_NAME %%%.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    organization.org/host: {{ $organizationHost }}
